Output demo_workflows.gif

Set FontSize 18
Set Width 1400
Set Height 1000

Hide
Type@1ms "sauron -c $HOME/tools/sauron/demo_config.yaml"
Enter
Sleep 2s
Down@200ms 9
Sleep 1s
Show

# Open the workflows
Tab
Sleep 1s
# Go to the first workflow and open it
Down
Sleep 1ms
Tab
Sleep 1s
# Go to the first job and open it
Down
Sleep 1ms
Tab
Sleep 1s
# Open the first log entry
Down 1
Sleep 1s
Tab
Sleep 1s
Type "z"

# Final sleep
Sleep 5s
