
settings:
  check_period: 600000000

nodes:
- type: notifications
- type: issues
  display_name: "My Issues"
  query: "is:issue state:open archived:false assignee:@me sort:updated-desc"
- type: heading
  display_name: "My Pulls"
  open: true
  children:
  - type: pulls
    display_name: "Needs your review"
    query: "is:pr is:open review-requested:@me sort:updated-desc"
  - type: pulls
    display_name: "Needs action"
    query: "is:pr is:open author:@me review:changes_requested sort:updated-desc"
  - type: pulls
    display_name: "Ready to merge"
    query: "is:pr is:open author:@me review:approved sort:updated-desc"
- type: heading
  display_name: "Core"
  open: true
  children:
  - name: codedownio/codedown
    settings:
      check_period: 300000000
  - codedownio/codedown-db
  - codedownio/codedown-languages
  - codedownio/job-manager
  - codedownio/matheditable
  - codedownio/ot
  - codedownio/resource-map
- type: heading
  display_name: "Notebook language servers"
  open: true
  children:
  - codedownio/cpp-notebook-language-server
  - codedownio/go-notebook-language-server
  - codedownio/haskell-notebook-language-server
  - codedownio/rust-notebook-language-server
- type: heading
  display_name: "Languages ecosystem"
  open: true
  children:
  - codedownio/markdown-spellcheck-lsp
  - codedownio/General
- type: heading
  display_name: "Open source"
  open: true
  children:
  - codedownio/aeson-typescript
  - codedownio/myers-diff
  - codedownio/nixpkgs-slim
  - codedownio/sandwich
  - codedownio/servant-typescript
  - codedownio/sauron
- type: heading
  display_name: "Maintaining"
  open: true
  children:
  - haskell-fswatch/hfsnotify
  - haskell-webdriver/haskell-webdriver
- type: heading
  display_name: "No tests"
  open: true
  children:
  - codedownio/immutability-helper-rfc6902
  - codedownio/julia2nix
  - codedownio/registry2nix
