
settings:
  green_if: ci_green_on_default_branch
  check_period: 600000000
    # is_green: 60000000
    # is_green: 10m

sections:
- display_name: "Core"
  repos:
  - name: codedownio/codedown
    settings:
      check_period: 300000000
      # check_period: 5m
  - codedownio/codedown-languages
  - codedownio/ot
  - codedownio/matheditable
- display_name: "Languages ecosystem"
  repos:
  - codedownio/haskell-notebook-language-server
  - codedownio/markdown-spellcheck-lsp
  - codedownio/rust-notebook-language-server
  - codedownio/General
- display_name: "Open source"
  repos:
  - codedownio/aeson-typescript
  - codedownio/myers-diff
  - codedownio/sandwich
  - codedownio/servant-typescript
  - codedownio/sauron
- display_name: "Maintaining"
  repos:
  - haskell-fswatch/hfsnotify
  - haskell-webdriver/haskell-webdriver
- display_name: "No tests"
  open: false
  repos:
  - codedownio/immutability-helper-rfc6902
  - codedownio/julia2nix
  - codedownio/registry2nix

# - display_name: "thomasjm"
#   open: false
#   repos:
#   - "thomasjm/*"
# - display_name: "codedownio"
#   open: false
#   repos:
#   - "codedownio/*"
