name:                sauron
version:             0.1.0.0
github:              "codedownio/sauron"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2023 Tom McLaughlin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sauron#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- commonmark
- commonmark-extensions
- commonmark-pandoc
- containers
- github
- http-client
- microlens
- mtl
- pandoc-types
- process
- relude
- stm
- string-interpolate
- text
- time
- unliftio-core
- unliftio
- vector
- vty
- vty-crossplatform

default-extensions:
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- NumericUnderscores
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - microlens-th
  - time
  - vector

executables:
  sauron:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - exceptions
    - filepath
    - optparse-applicative
    - safe-exceptions
    - sauron
    - yaml

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sauron
