
resolver: lts-22.36

packages:
- .

nix:
  pure: false
  packages:
  - pcre
  - zlib
  path:
  - "nixpkgs=/home/tom/tools/nixpkgs"

extra-deps:
- vty-windows-0.1.0.1

# - github-0.29

- git: https://github.com/codedownio/github.git
  # main branch, which has some changes from upstream:
  # - fixes for search query escaping
  # - support for detailed pagination
  commit: 772b9f1039663c96db77dc14570fbffd6e833e17

- git: https://github.com/dogonthehorizon/git-config.git
  commit: 8f3fab100e4c8d82b5c6fe7c0cc09510249e98cf
