
resolver: lts-22.13

packages:
- .

nix:
  pure: false
  packages:
  - zlib
  path:
  - "nixpkgs=/home/tom/tools/nixpkgs"

extra-deps:
- vty-windows-0.1.0.1

# - github-0.29

- git: git@github.com:codedownio/github.git
  # per-page-query-v2 branch
  commit: cd32569e3b4572158ce240096a79633607b08e0a
