
resolver: lts-23.6

packages:
- .

nix:
  pure: false
  packages:
  - pcre
  - zlib
  path:
  - "nixpkgs=/home/tom/tools/nixpkgs"

extra-deps:
- vty-windows-0.2.0.3

# - github-0.29

- git: https://github.com/codedownio/github.git
  # main branch, which has some changes from upstream:
  # - fixes for search query escaping
  # - support for detailed pagination
  commit: 772b9f1039663c96db77dc14570fbffd6e833e17

- git: https://github.com/dogonthehorizon/git-config.git
  commit: 8f3fab100e4c8d82b5c6fe7c0cc09510249e98cf

# This is forked solely to remove a couple problematic lines from the cabal files; see
# https://github.com/input-output-hk/haskell.nix/issues/2312
- git: https://github.com/thomasjm/vty-crossplatform.git
  commit: 030ceab629d5c888a4a890e2aa7f1e0e6eda0578
