
resolver: nightly-2025-09-22

packages:
- .
# - /home/tom/tools/github

nix:
  enable: false

system-ghc: true

extra-deps:
- vty-windows-0.2.0.3
- brick-skylighting-1.0@sha256:64764b6be36c05261959f68ed38b9cb37e1acb6180a3bde5dd98255f62ea7e3b,1812

# - github-0.29

- git: https://github.com/codedownio/github.git
  # sauron-sep18-2025 branch, which has some changes from upstream:
  # - fixes for search query escaping
  # - fix Job type to make some fields optional
  # - fix JobStep type to make some fields optional
  # - Repo: add subscribers_count
  # - Fix getNotificationsR
  # - EventType: add more constructors + a catchall called Unknown
  # - Fix markNotificationAsReadR
  # - Add markNotificationAsDoneR
  commit: 23294bf9e64c358f2c907d12bd88e89696c34818

- git: https://github.com/dogonthehorizon/git-config.git
  commit: 8f3fab100e4c8d82b5c6fe7c0cc09510249e98cf

# This is forked solely to remove a couple problematic lines from the cabal files; see
# https://github.com/input-output-hk/haskell.nix/issues/2312
- git: https://github.com/thomasjm/vty-crossplatform.git
  commit: 030ceab629d5c888a4a890e2aa7f1e0e6eda0578
