
resolver: lts-22.12

packages:
- .

nix:
  pure: false
  packages:
  - zlib

extra-deps:
- vty-6.0
- vty-crossplatform-0.1.0.0
- vty-unix-0.1.0.0
- vty-windows-0.1.0.1
- brick-2.0

# - github-0.29

- git: git@github.com:codedownio/github.git
  # per-page-query-v2 branch
  commit: cd32569e3b4572158ce240096a79633607b08e0a
