
resolver: lts-22.13

packages:
- .

nix:
  pure: false
  packages:
  - zlib
  path:
  - "nixpkgs=/home/tom/tools/nixpkgs"

extra-deps:
- vty-windows-0.1.0.1

# - github-0.29

- git: git@github.com:codedownio/github.git
  # main branch
  commit: 772b9f1039663c96db77dc14570fbffd6e833e17
