#!/usr/bin/env bash

set -eo pipefail

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPTDIR/.."

for tape in *.tape; do
  echo "Generating $tape..."
  vhs "$tape"
done

echo "Done!"
